# Generated by Django 3.0.1 on 2021-11-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20211105_2103'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fav_audio',
            field=models.ManyToManyField(to='music.Audio'),
        ),
    ]
