# Generated by Django 3.0.1 on 2021-10-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('artist', models.CharField(max_length=20)),
                ('song', models.FileField(upload_to='')),
                ('label', models.ImageField(upload_to='')),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('duration', models.CharField(max_length=30)),
            ],
        ),
    ]
