# Generated by Django 3.0.1 on 2021-11-02 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('music', '0002_auto_20211030_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio', to='profiles.UserProfile'),
        ),
    ]
