# Generated by Django 3.0.1 on 2021-11-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('music', '0004_auto_20211102_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio', to='profiles.UserProfile'),
        ),
    ]
