# Generated by Django 3.0.1 on 2021-11-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_fav_audio'),
        ('music', '0005_auto_20211105_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='favourite_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audi', to='profiles.UserProfile'),
        ),
    ]
