# Generated by Django 3.0.1 on 2021-12-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_audio_favourite_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='favourite_by',
        ),
    ]
