# Generated by Django 3.2.6 on 2021-12-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_audio_favourite_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
