# Generated by Django 3.0.1 on 2021-12-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_audio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='duration',
        ),
        migrations.AlterField(
            model_name='audio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
