# Generated by Django 3.0.1 on 2021-12-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20211226_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='label',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
