# Generated by Django 3.0.1 on 2021-10-22 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211021_1643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
